#	$OpenBSD: sshd_config,v 1.103 2018/04/09 20:41:22 tj Exp $

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

# If you want to change the port on a SELinux system, you have to tell
# SELinux about this change.
# semanage port -a -t ssh_port_t -p tcp #PORTNUMBER
#
#Port: "22"
#AddressFamily: "any"
#ListenAddress: "0.0.0.0"
#ListenAddress: "::"

Hostkey: ["/etc/ssh/ssh_host_rsa_key","/etc/ssh/ssh_host_ecdsa_key","/etc/ssh/ssh_host_ed25519_key"]

# Ciphers and keying
#RekeyLimit default: "none"

# This system is following system-wide crypto policy. The changes to
# crypto properties (Ciphers, MACs, ...) will not have any effect here.
# They will be overridden by command-line options passed to the server
# on command line.
# Please, check manual pages for update-crypto-policies(8) and sshd_config(5).

# Logging
#SyslogFacility: "AUTH"
SyslogFacility: "AUTHPRIV"
LogLevel: "INFO"

# Authentication:

#LoginGraceTime: "2m"
#SV-230288r627750_rule
StrictModes: 'yes'
#MaxAuthTries: "6"
#MaxSessions: "10"

#PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile: ".ssh/authorized_keys"

#AuthorizedPrincipalsFile: "none"

#AuthorizedKeysCommand: "none"
#AuthorizedKeysCommandUser: "nobody"

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#HostbasedAuthentication: "no"
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
IgnoreUserKnownHosts: 'yes'
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts: "yes"

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication: "yes"
# SV-230380r743993_rule
PermitEmptyPasswords: 'no'
PasswordAuthentication: 'yes'

# Change to no to disable s/key passwords
#ChallengeResponseAuthentication: "yes"
ChallengeResponseAuthentication: 'no'

# Kerberos options
#SV-230291r743957_rule
KerberosAuthentication: 'no'
#KerberosOrLocalPasswd: "yes"
#KerberosTicketCleanup: "yes"
#KerberosGetAFSToken: "no"
#KerberosUseKuserok: "yes"

# GSSAPI options
GSSAPICleanupCredentials: 'no'
#GSSAPIStrictAcceptorCheck: "yes"
#GSSAPIKeyExchange: "no"
#GSSAPIEnablek5users: "no"

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
# WARNING: 'UsePAM no' is not supported in Fedora and may cause several
# problems.
UsePAM: 'yes'

#AllowAgentForwarding: yes
#AllowTcpForwarding: yes
#GatewayPorts: no
#X11DisplayOffset: 10
#SV-230556r62750_rule
X11UseLocalhost: 'yes'
#PermitTTY: yes

# It is recommended to use pam_motd in /etc/pam.d/sshd instead of PrintMotd,
# as it is more configurable and versatile than the built-in version.
PrintMotd: 'no'
#SV-230382r627750_rule
PrintLastLog: 'yes'
#TCPKeepAlive: yes
PermitUserEnvironment: 'no'
#UseDNS: no
#PidFile: /var/run/sshd.pid
#MaxStartups: 10:30:100
#PermitTunnel: no
#ChrootDirectory: none
#VersionAddendum: none

# no default banner path
#Banner: none

# Accept locale-related environment variables
AcceptEnv: [ LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES, LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT, LC_IDENTIFICATION LC_ALL LANGUAGE, XMODIFIERS ]

# override default of no subsystems
Subsystem: "sftp /usr/libexec/openssh/sftp-server"

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	X11Forwarding no
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server
#SV-230296r627750_rule
PermitRootLogin: 'no'
#SV-230225r627750_rule
Banner: /etc/issue
#SV-230244r743934_rule
ClientAliveCountMax: 0
ClientAliveInterval: 600

# Per CCE-80895-6: Set Compression no in /etc/ssh/sshd_config
#SV-230289r743954_rule
Compression: 'no'
#SV-230244r743934_rule
RekeyLimit: 1G 1h
X11Forwarding: 'no'
GSSAPIAuthentication: 'no'


