---
- name: Configure package requirements
  hosts: "*"
  become: true
  vars_files:
    - /home/admin/RMF/apply/redhat/OS8/vars/package.yml
  tasks:
   
    - name: install required packages
      dnf:
        name: 
          - "{{install[0]}}"
          - "{{install[1]}}"
          - "{{install[2]}}"
          - "{{install[3]}}"
          - "{{install[4]}}"
          - "{{install[5]}}"
        state: present
    
    - name: remove non-compliant packages
      dnf:
        name: 
          - "{{remove[0]}}"
          - "{{remove[1]}}"
          - "{{remove[2]}}"

        state: absent
