---
- name: Configure Misc Items 
  hosts: "*"
  become: yes
  tasks:
    
    - name: Gather the package facts
      package_facts:
        manager: auto
   
    - name: Disable services 
      systemd:
        name: "{{item}}" 
        enabled: 'no'
        state: stopped
        masked: 'yes'
      loop:
        - kdump.service
        - kdump.socket
        - ctrl-alt-del.target 
      ignore_errors: 'yes'

    - name: Enable service fapolicyd
      service:
        name: fapolicyd
        enabled: 'yes'
        state: started
        masked: 'no'
      when:
        - '"fapolicyd" in ansible_facts.packages'



    - name: Prevent Unrestricted Mail Relaying
      block:

        - name: Check for duplicate values
          lineinfile:
            path: /etc/postfix/main.cf
            create: false
            regexp: ^[ \t]*smtpd_client_restrictions\s*=\s*
            state: absent
          check_mode: true
          changed_when: false
          register: dupes

        - name: Deduplicate values from /etc/postfix/main.cf
          lineinfile:
            path: /etc/postfix/main.cf
            create: false
            regexp: ^[ \t]*smtpd_client_restrictions\s*=\s*
            state: absent
          when: dupes.found is defined and dupes.found > 1

        - name: Insert correct line to /etc/postfix/main.cf
          lineinfile:
            path: /etc/postfix/main.cf
            create: true
            regexp: ^[ \t]*smtpd_client_restrictions\s*=\s*
            line: smtpd_client_restrictions = permit_mynetworks,reject
            state: present
          when: '"postfix" in ansible_facts.packages'

        - name: Disable chrony daemon from acting as server
          block:
            - name: Check for duplicate values
              lineinfile:
                path: /etc/chrony.conf
                create: false
                regexp: ^\s*port\s+
                state: absent
              check_mode: true
              changed_when: false
              register: dupes

            - name: Deduplicate values from /etc/chrony.conf
              lineinfile:
                path: /etc/chrony.conf
                create: false
                regexp: ^\s*port\s+
                state: absent
              when: dupes.found is defined and dupes.found > 1

            - name: Insert correct line to /etc/chrony.conf
              lineinfile:
                path: /etc/chrony.conf
                create: true
                regexp: ^\s*port\s+
                line: port 0
                state: present
