---
- name: Configuring USB Gaurd 
  hosts: "*"
  become: yes
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Generate USBGuard Policy
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Check that the /etc/usbguard/rules.conf exists
          stat:
            path: /etc/usbguard/rules.conf
          register: policy_file

        - name: Create USBGuard Policy configuration
          command: usbguard generate-policy
          register: policy
          when: not policy_file.stat.exists or policy_file.stat.size == 0

        - name: Copy the Generated Policy configuration to a persistent file
          copy:
            content: '{{ policy.stdout }}'
            dest: /etc/usbguard/rules.conf
            mode: 384
          when: not policy_file.stat.exists or policy_file.stat.size == 0

        - name: Add comment into /etc/usbguard/rules.conf when system has no USB devices
          lineinfile:
            path: /etc/usbguard/rules.conf
            line: '# No USB devices found'
            state: present
          when: not policy_file.stat.exists or policy_file.stat.size == 0

        - name: Enable service usbguard
          service:
            name: usbguard
            enabled: 'yes'
            state: started
            masked: 'no'
          when:
          - '"usbguard" in ansible_facts.packages'
