---
- name: Configuring Chrony / NTP 
  hosts: "*"
  become: yes
  tasks:
    
    - name: Gather the package facts
      package_facts:
        manager: auto
   

    - name: Disable chrony daemon from acting as server
      block:
        - name: Check for duplicate values
          lineinfile:
            path: /etc/chrony.conf
            create: false
            regexp: ^\s*port\s+
            state: absent
          check_mode: true
          changed_when: false
          register: dupes

    - name: Deduplicate values from /etc/chrony.conf
      lineinfile:
        path: /etc/chrony.conf
        create: false
        regexp: ^\s*port\s+
        state: absent
      when: dupes.found is defined and dupes.found > 1

    - name: Insert correct line to /etc/chrony.conf
      lineinfile:
        path: /etc/chrony.conf
        create: true
        regexp: ^\s*port\s+
        line: port 0
        state: present

    - name: Disable network management of chrony daemon
      block:
 
        - name: Check for duplicate values
          lineinfile:
            path: /etc/chrony.conf
            create: false
            regexp: ^\s*cmdport\s+
            state: absent
          check_mode: true
          changed_when: false
          register: dupes

        - name: Deduplicate values from /etc/chrony.conf
          lineinfile:
            path: /etc/chrony.conf
            create: false
            regexp: ^\s*cmdport\s+
            state: absent
          when: dupes.found is defined and dupes.found > 1

        - name: Insert correct line to /etc/chrony.conf
          lineinfile:
            path: /etc/chrony.conf
            create: true
            regexp: ^\s*cmdport\s+
            line: cmdport 0

    - name:
      set_fact:
        var_time_service_set_maxpoll: !!str 16


    - name: XCCDF Value var_time_service_set_maxpoll # promote to variable
      block:
      

        - name: Check that /etc/ntp.conf exist
          stat:
            path: /etc/ntp.conf
          register: ntp_conf_exist_result
          when:
            - ( "chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages )

        - name: Check that /etc/chrony.conf exist
          stat:
            path: /etc/chrony.conf
          register: chrony_conf_exist_result
          when:
            - ( "chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages )

        - name: Update the maxpoll values in /etc/ntp.conf
          replace:
            path: /etc/ntp.conf
            regexp: ^(server.*maxpoll)[ ]+[0-9]+(.*)$
            replace: \1 {{ var_time_service_set_maxpoll }}\2
          when:
            - ( "chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages )
            - ntp_conf_exist_result.stat.exists

        - name: Update the maxpoll values in /etc/chrony.conf
          replace:
            path: /etc/chrony.conf
            regexp: ^((?:server|pool|peer).*maxpoll)[ ]+[0-9]+(.*)$
            replace: \1 {{ var_time_service_set_maxpoll }}\2
          when:
            - ( "chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages )
            - chrony_conf_exist_result.stat.exists

        - name: Set the maxpoll values in /etc/ntp.conf
          replace:
            path: /etc/ntp.conf
            regexp: (^server\s+((?!maxpoll).)*)$
            replace: \1 maxpoll {{ var_time_service_set_maxpoll }}\n
          when:
            - ( "chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages )
            - ntp_conf_exist_result.stat.exists
         
        - name: Set the maxpoll values in /etc/chrony.conf
          replace:
            path: /etc/chrony.conf
            regexp: (^(?:server|pool|peer)\s+((?!maxpoll).)*)$
            replace: \1 maxpoll {{ var_time_service_set_maxpoll }}\n
          when:
            - ( "chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages )
            - chrony_conf_exist_result.stat.exists
